# Generated by Django 3.2.6 on 2021-08-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('description', models.CharField(max_length=500, verbose_name='Açıklama')),
                ('link', models.CharField(max_length=50, verbose_name='Web Site Linki')),
                ('email', models.CharField(max_length=50, verbose_name='E-Posta')),
                ('image', models.ImageField(upload_to='', verbose_name='Resim')),
                ('statu', models.BooleanField(verbose_name='Statu')),
                ('code', models.CharField(max_length=32, verbose_name='Form Doğrulama Kodu')),
            ],
        ),
    ]
